
import React, { useState } from 'react';
import Header from '../components/Header';
import FractionExplorer from '../components/interactive/FractionExplorer';
import GraphPlotter from '../components/interactive/GraphPlotter';
import ProbabilityEngine from '../components/interactive/ProbabilityEngine';
import LogicEngine from '../components/interactive/LogicEngine';

import generatedLevels from '../data/generated-levels.json';

export default function LearningLab() {

    // --- SCENARIO DATA (Generated by LLM) ---
    const mathChallenges = generatedLevels.graphChallenges;
    const logicChallenges = generatedLevels.logicPuzzles;

    const getRandomLevel = (list) => list[Math.floor(Math.random() * list.length)];

    const [activeMathLevel, setActiveMathLevel] = useState(mathChallenges[0]);
    const [activeLogicLevel, setActiveLogicLevel] = useState(logicChallenges[0]);

    const nextMath = () => setActiveMathLevel(getRandomLevel(mathChallenges));
    const nextLogic = () => setActiveLogicLevel(getRandomLevel(logicChallenges));

    return (
        <div className="min-h-screen bg-gray-50 pb-20">
            <Header />

            <div className="container-app py-12">
                <div className="text-center mb-16">
                    <span className="badge badge-accent mb-4">Beta Feature</span>
                    <h1 className="text-4xl font-bold text-dark-50 mb-4">Interactive Learning Lab 🧪</h1>
                    <p className="text-xl text-dark-300 max-w-2xl mx-auto mb-8">
                        Explore math and logic through interactive experiments.
                    </p>

                    {/* How to Use / Tutorial Box */}
                    <div className="max-w-3xl mx-auto bg-blue-50 border border-blue-100 rounded-xl p-6 text-left">
                        <h3 className="font-bold text-blue-800 mb-2 flex items-center gap-2">
                            <span className="text-xl">ℹ️</span> How to use the Lab
                        </h3>
                        <ul className="grid md:grid-cols-2 gap-4 text-sm text-blue-900">
                            <li className="flex items-start gap-2">
                                <span className="bg-blue-200 text-blue-800 rounded-full w-5 h-5 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">1</span>
                                <div>
                                    <strong>Choose a Level:</strong> Click the pill buttons (e.g., "Level One") to load a specific challenge.
                                </div>
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="bg-blue-200 text-blue-800 rounded-full w-5 h-5 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">2</span>
                                <div>
                                    <strong>Interact:</strong> Move sliders or toggle switches to solve the puzzle.
                                </div>
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="bg-blue-200 text-blue-800 rounded-full w-5 h-5 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">3</span>
                                <div>
                                    <strong>Win:</strong> When you match the target line or light up the bulb, you'll get a "Correct!" confirmation.
                                </div>
                            </li>
                            <li className="flex items-start gap-2">
                                <span className="bg-blue-200 text-blue-800 rounded-full w-5 h-5 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">4</span>
                                <div>
                                    <strong>Free Play:</strong> Scroll down to "Free Play" to experiment without goals.
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <div className="space-y-24">

                    {/* SCENARIO DEMO 1: Math Challenges */}
                    <section className="bg-white p-8 rounded-3xl border border-dark-100 shadow-sm relative overflow-hidden">
                        <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-primary-400 to-primary-600" />

                        <div className="text-center mb-8">
                            <span className="text-sm font-bold text-primary-600 uppercase tracking-widest">Engine 1: GraphPlotter</span>
                            <h2 className="text-3xl font-bold text-dark-50 mt-1 mb-4">Challenge Mode: Match the Line</h2>
                            <p className="text-dark-400 max-w-xl mx-auto">
                                Instead of just "playing", the engine now sets a goal.
                                Click a level below to inject new parameters into the engine instantly.
                            </p>
                        </div>

                        {/* Level Controls */}
                        <div className="flex flex-col items-center gap-4 mb-8">
                            <div className="text-sm font-bold text-dark-300 uppercase tracking-widest">
                                Data Pool: {mathChallenges.length} Levels
                            </div>

                            <div className="flex flex-wrap justify-center gap-2">
                                {/* Show just first 5 as quick access */}
                                {mathChallenges.slice(0, 5).map((level) => (
                                    <button
                                        key={level.id}
                                        onClick={() => setActiveMathLevel(level)}
                                        className={`px-3 py-1 rounded-full font-bold text-xs transition-all ${activeMathLevel.id === level.id
                                                ? 'bg-dark-50 text-white'
                                                : 'bg-gray-100 text-dark-300 hover:bg-gray-200'
                                            }`}
                                    >
                                        #{level.id}
                                    </button>
                                ))}
                            </div>

                            <button
                                onClick={nextMath}
                                className="px-8 py-3 bg-primary-600 hover:bg-primary-700 text-white rounded-xl font-bold shadow-lg hover:shadow-xl transition-all transform hover:scale-105 active:scale-95 flex items-center gap-2"
                            >
                                <span>🎲</span> Shuffle: Load Random Level
                            </button>
                        </div>

                        {/* The Engine Instance */}
                        <GraphPlotter
                            isChallenge={true}
                            targetSlope={activeMathLevel.slope}
                            targetIntercept={activeMathLevel.intercept}
                            key={activeMathLevel.id} // Force re-render on level change
                        />
                    </section>


                    {/* SCENARIO DEMO 2: Logic Puuzles */}
                    <section className="bg-white p-8 rounded-3xl border border-dark-100 shadow-sm relative overflow-hidden">
                        <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-accent-400 to-accent-600" />

                        <div className="text-center mb-8">
                            <span className="text-sm font-bold text-accent-600 uppercase tracking-widest">Engine 2: LogicEngine</span>
                            <h2 className="text-3xl font-bold text-dark-50 mt-1 mb-4">Challenge Mode: Circuit Breaker</h2>
                            <p className="text-dark-400 max-w-xl mx-auto">
                                The same engine, reconfigured as a puzzle.
                            </p>
                        </div>

                        {/* Level Controls */}
                        <div className="flex flex-col items-center gap-4 mb-8">
                            <div className="text-sm font-bold text-dark-300 uppercase tracking-widest">
                                Data Pool: {logicChallenges.length} Puzzles
                            </div>

                            <div className="flex flex-wrap justify-center gap-2">
                                {/* Show just first 5 as quick access */}
                                {logicChallenges.slice(0, 5).map((level) => (
                                    <button
                                        key={level.id}
                                        onClick={() => setActiveLogicLevel(level)}
                                        className={`px-3 py-1 rounded-full font-bold text-xs transition-all ${activeLogicLevel.id === level.id
                                                ? 'bg-dark-50 text-white'
                                                : 'bg-gray-100 text-dark-300 hover:bg-gray-200'
                                            }`}
                                    >
                                        #{level.id}
                                    </button>
                                ))}
                            </div>

                            <button
                                onClick={nextLogic}
                                className="px-8 py-3 bg-accent-600 hover:bg-accent-700 text-white rounded-xl font-bold shadow-lg hover:shadow-xl transition-all transform hover:scale-105 active:scale-95 flex items-center gap-2"
                            >
                                <span>🎲</span> Shuffle: Load Random Puzzle
                            </button>
                        </div>

                        <LogicEngine
                            isChallenge={true}
                            challenge={activeLogicLevel}
                            key={activeLogicLevel.id}
                        />
                    </section>


                    {/* Playground Section */}
                    <div className="grid md:grid-cols-2 gap-8">
                        <div className="bg-white p-8 rounded-3xl border border-gray-200">
                            <h3 className="text-xl font-bold mb-4">🔬 Free Play: Statistics</h3>
                            <ProbabilityEngine />
                        </div>
                        <div className="bg-white p-8 rounded-3xl border border-gray-200">
                            <h3 className="text-xl font-bold mb-4">🍰 Free Play: Fractions</h3>
                            <FractionExplorer />
                        </div>
                    </div>

                </div>
            </div>
        </div>
    );
}
